--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "santosh"."COMMENTS" DROP CONSTRAINT "VID_FK";

ALTER TABLE "santosh"."COMMENTS" DROP CONSTRAINT "COMMENTS_PK";

DROP TABLE "santosh"."COMMENTS";

CREATE TABLE "santosh"."COMMENTS" (
		"COM_ID" VARCHAR(20) NOT NULL,
		"CONTENT" VARCHAR(500) NOT NULL,
		"COMMENT_DATE" DATE NOT NULL DEFAULT CURRENT DATE,
		"VID" VARCHAR(20) NOT NULL,
		"RID" VARCHAR(20)
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1";

ALTER TABLE "santosh"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY
	("COM_ID");

ALTER TABLE "santosh"."COMMENTS" ADD CONSTRAINT "VID_FK" FOREIGN KEY
	("VID")
	REFERENCES "santosh"."VALIDATED_ARTICLES"
	("VID");

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='',
		VALCOUNT=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='',
		VALCOUNT=7
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='',
		VALCOUNT=7
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=1,
		DISTCOUNT=1
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='1',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='101',
		VALCOUNT=2,
		DISTCOUNT=2
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='104',
		VALCOUNT=5,
		DISTCOUNT=5
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='109',
		VALCOUNT=7,
		DISTCOUNT=7
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='141',
		VALCOUNT=9,
		DISTCOUNT=9
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=5;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='144',
		VALCOUNT=12,
		DISTCOUNT=12
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=6;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='146',
		VALCOUNT=14,
		DISTCOUNT=14
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=7;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='148',
		VALCOUNT=16,
		DISTCOUNT=16
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=8;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='151',
		VALCOUNT=19,
		DISTCOUNT=19
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=9;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2',
		VALCOUNT=40
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2',
		VALCOUNT=7
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-02-16',
		VALCOUNT=1
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-20',
		VALCOUNT=1
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-20',
		VALCOUNT=11
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-20',
		VALCOUNT=12
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-21',
		VALCOUNT=12
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-21',
		VALCOUNT=13
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-21',
		VALCOUNT=25
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=5;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-22',
		VALCOUNT=25
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=6;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-22',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=7;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-22',
		VALCOUNT=8
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-23',
		VALCOUNT=11
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-23',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=8;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-23',
		VALCOUNT=44
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=9;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='22',
		VALCOUNT=21,
		DISTCOUNT=21
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=10;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='25',
		VALCOUNT=23,
		DISTCOUNT=23
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=11;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='27',
		VALCOUNT=25,
		DISTCOUNT=25
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=12;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='3',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='3',
		VALCOUNT=39
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='3',
		VALCOUNT=4
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='3',
		VALCOUNT=41
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=5;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='3',
		VALCOUNT=44
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=6;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='3',
		VALCOUNT=6
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='30',
		VALCOUNT=28,
		DISTCOUNT=28
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=13;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='32',
		VALCOUNT=30,
		DISTCOUNT=30
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=14;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='42',
		VALCOUNT=32,
		DISTCOUNT=32
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=15;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='45',
		VALCOUNT=35,
		DISTCOUNT=35
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=16;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='47',
		VALCOUNT=37,
		DISTCOUNT=37
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=17;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='49',
		VALCOUNT=39,
		DISTCOUNT=39
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=18;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='52',
		VALCOUNT=42,
		DISTCOUNT=42
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=19;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='81',
		VALCOUNT=44,
		DISTCOUNT=44
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=20;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='anwesha roy is a good writer',
		VALCOUNT=3
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='anwesha roy is a good writer',
		VALCOUNT=9
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='arpan is a good writer',
		VALCOUNT=11
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='heloooo dude!!!!',
		VALCOUNT=14
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=5;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='hey santosh this aint a bad artic',
		VALCOUNT=16
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=6;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='hey..',
		VALCOUNT=18
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=7;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='hgfdshgsjdhgj',
		VALCOUNT=20
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=8;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='hi santosh..',
		VALCOUNT=22
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=9;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='hjhjh',
		VALCOUNT=2
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='hjhjh',
		VALCOUNT=24
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=10;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='jhinkuu',
		VALCOUNT=27
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=11;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='kjhdkrjo',
		VALCOUNT=2
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='kjhdkrjo',
		VALCOUNT=29
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=12;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='klop',
		VALCOUNT=31
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=13;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='ngjgjjg',
		VALCOUNT=33
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=14;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='null',
		VALCOUNT=40
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=5;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='null',
		VALCOUNT=44
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=6;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='null',
		VALCOUNT=5
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='rgjyhjcvcf',
		VALCOUNT=35
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=15;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='santosh heloooo',
		VALCOUNT=37
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=16;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='ssssssssssssssssswwwwwwwwwwwwwwww',
		VALCOUNT=40
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=17;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='tukiiii',
		VALCOUNT=42
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=18;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='zinnia is a good writer',
		VALCOUNT=2
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=5;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='zinnia is a good writer',
		VALCOUNT=44
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=19;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='zinnia is a good writer',
		VALCOUNT=44
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=20;

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=3,
		HIGH2KEY='3',
		LOW2KEY='1',
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'VID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=3,
		HIGH2KEY='null',
		LOW2KEY='1',
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'RID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=33,
		HIGH2KEY='tukiiii',
		LOW2KEY='anwesha roy is a good writer',
		AVGCOLLEN=17,
		NUMNULLS=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'CONTENT' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=44,
		HIGH2KEY='61',
		LOW2KEY='101',
		AVGCOLLEN=6,
		NUMNULLS=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COM_ID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=5,
		HIGH2KEY='2012-03-22',
		LOW2KEY='2012-03-20',
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='COMMENTS' AND COLNAME = 'COMMENT_DATE' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.INDEXES 
	SET NLEAF=1,
		NLEVELS=1,
		FIRSTKEYCARD=44,
		FIRST2KEYCARD=-1,
		FULLKEYCARD=44,
		CLUSTERRATIO=100,
		SEQUENTIAL_PAGES=0,
		DENSITY=0,
		NUMRIDS=45,
		NUMRIDS_DELETED=1,
		NUM_EMPTY_LEAFS=0,
		AVERAGE_RANDOM_PAGES=1.0,
		AVERAGE_SEQUENCE_GAP=0.0,
		AVERAGE_SEQUENCE_PAGES=0.0,
		DATAPARTITION_CLUSTERFACTOR=1.0,
		INDCARD=44
	WHERE TABNAME ='COMMENTS' AND INDNAME = 'COMMENTS_PK' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.TABLES 
	SET CARD=44,
		NPAGES=1,
		FPAGES=1,
		OVERFLOW=0,
		ACTIVE_BLOCKS=0,
		AVGCOMPRESSEDROWSIZE=0,
		AVGROWCOMPRESSIONRATIO=0.0,
		PCTROWSCOMPRESSED=0.0,
		PCTPAGESSAVED=0.0
	WHERE TABNAME ='COMMENTS' AND TABSCHEMA='santosh';

