--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "santosh"."ISSUES" DROP CONSTRAINT "ISSUES_PK";

DROP TABLE "santosh"."ISSUES";

CREATE TABLE "santosh"."ISSUES" (
		"NAME" VARCHAR(15) NOT NULL,
		"COVER_PICTURE" VARCHAR(50) NOT NULL,
		"DOWNLOAD_COUNT" INTEGER NOT NULL DEFAULT 0,
		"FILE_PATH" VARCHAR(50) NOT NULL,
		"DATE" DATE NOT NULL DEFAULT CURRENT DATE
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1";

ALTER TABLE "santosh"."ISSUES" ADD CONSTRAINT "ISSUES_PK" PRIMARY KEY
	("NAME");

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='',
		VALCOUNT=0
	WHERE TABNAME ='ISSUES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='',
		VALCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh'
	AND TYPE='F'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='',
		VALCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2011-12-19',
		VALCOUNT=1
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-01-19',
		VALCOUNT=2
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-19',
		VALCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='2012-03-19',
		VALCOUNT=4
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DATE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='DEC-2012',
		VALCOUNT=1,
		DISTCOUNT=1
	WHERE TABNAME ='ISSUES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='FEB-2012',
		VALCOUNT=2,
		DISTCOUNT=2
	WHERE TABNAME ='ISSUES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='JANUARY-2012',
		VALCOUNT=3,
		DISTCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='MARCH 2012',
		VALCOUNT=4,
		DISTCOUNT=4
	WHERE TABNAME ='ISSUES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='Pdf/Getting Started.pdf',
		VALCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='Pdf/Getting Started.pdf',
		VALCOUNT=4
	WHERE TABNAME ='ISSUES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='images/homepage_images/blue-item-',
		VALCOUNT=1
	WHERE TABNAME ='ISSUES' AND COLNAME = 'COVER_PICTURE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='images/homepage_images/green-item',
		VALCOUNT=2
	WHERE TABNAME ='ISSUES' AND COLNAME = 'COVER_PICTURE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='images/homepage_images/yellow-ite',
		VALCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'COVER_PICTURE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE='images/homepage_images/yellow-ite',
		VALCOUNT=4
	WHERE TABNAME ='ISSUES' AND COLNAME = 'COVER_PICTURE' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE=21,
		VALCOUNT=1
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DOWNLOAD_COUNT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=1;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE=45,
		VALCOUNT=2
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DOWNLOAD_COUNT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=2;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE=78,
		VALCOUNT=3
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DOWNLOAD_COUNT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=3;

UPDATE SYSSTAT.COLDIST 
	SET COLVALUE=78,
		VALCOUNT=4
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DOWNLOAD_COUNT' AND TABSCHEMA='santosh'
	AND TYPE='Q'
	AND SEQNO=4;

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=2,
		HIGH2KEY='Pdf/Getting Started.pdf',
		LOW2KEY='',
		AVGCOLLEN=10,
		NUMNULLS=0
	WHERE TABNAME ='ISSUES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=4,
		HIGH2KEY='2012-02-19',
		LOW2KEY='2012-01-19',
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DATE' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=4,
		HIGH2KEY='55',
		LOW2KEY='45',
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='ISSUES' AND COLNAME = 'DOWNLOAD_COUNT' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=4,
		HIGH2KEY='JANUARY-2012',
		LOW2KEY='FEB-2012',
		AVGCOLLEN=14,
		NUMNULLS=0
	WHERE TABNAME ='ISSUES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=4,
		HIGH2KEY='images/homepage_images/red-item-b',
		LOW2KEY='images/homepage_images/green-item',
		AVGCOLLEN=44,
		NUMNULLS=0
	WHERE TABNAME ='ISSUES' AND COLNAME = 'COVER_PICTURE' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.INDEXES 
	SET NLEAF=1,
		NLEVELS=1,
		FIRSTKEYCARD=4,
		FIRST2KEYCARD=-1,
		FULLKEYCARD=4,
		CLUSTERRATIO=100,
		SEQUENTIAL_PAGES=0,
		DENSITY=0,
		NUMRIDS=4,
		NUMRIDS_DELETED=0,
		NUM_EMPTY_LEAFS=0,
		AVERAGE_RANDOM_PAGES=1.0,
		AVERAGE_SEQUENCE_GAP=0.0,
		AVERAGE_SEQUENCE_PAGES=0.0,
		DATAPARTITION_CLUSTERFACTOR=1.0,
		INDCARD=4
	WHERE TABNAME ='ISSUES' AND INDNAME = 'ISSUES_PK' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.TABLES 
	SET CARD=4,
		NPAGES=1,
		FPAGES=1,
		OVERFLOW=0,
		ACTIVE_BLOCKS=0,
		AVGCOMPRESSEDROWSIZE=0,
		AVGROWCOMPRESSIONRATIO=0.0,
		PCTROWSCOMPRESSED=0.0,
		PCTPAGESSAVED=0.0
	WHERE TABNAME ='ISSUES' AND TABSCHEMA='santosh';

