--<ScriptOptions statementTerminator=";"/>

DROP SEQUENCE "santosh"."PENDING_ARTICLES_SEQ";

CREATE SEQUENCE "santosh"."PENDING_ARTICLES_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

