--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "santosh"."PENDING_ARTICLES" DROP CONSTRAINT "SQL120312132042420";

ALTER TABLE "santosh"."PENDING_ARTICLES" DROP CONSTRAINT "PENDING_ARTICLES_PK";

DROP TABLE "santosh"."PENDING_ARTICLES";

CREATE TABLE "santosh"."PENDING_ARTICLES" (
		"PID" VARCHAR(20) NOT NULL,
		"NAME" VARCHAR(60) NOT NULL,
		"CATEGORY" VARCHAR(30) NOT NULL DEFAULT '',
		"FILE_PATH" VARCHAR(150) NOT NULL DEFAULT '',
		"POST_DATE" DATE NOT NULL DEFAULT CURRENT DATE,
		"RID" VARCHAR(20) NOT NULL DEFAULT '',
		"CHECKED" VARCHAR(5) NOT NULL DEFAULT 'No',
		"PICTURE_PATH" VARCHAR(150),
		"SNIPPET" VARCHAR(500)
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1";

ALTER TABLE "santosh"."PENDING_ARTICLES" ADD CONSTRAINT "PENDING_ARTICLES_PK" PRIMARY KEY
	("PID");

ALTER TABLE "santosh"."PENDING_ARTICLES" ADD CONSTRAINT "SQL120312132042420" FOREIGN KEY
	("RID")
	REFERENCES "santosh"."REGISTERED_MEMBERS"
	("RID");

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'CATEGORY' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'CHECKED' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'PID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'POST_DATE' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'RID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'PICTURE_PATH' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ARTICLES' AND COLNAME = 'SNIPPET' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.INDEXES 
	SET NLEAF=1,
		NLEVELS=1,
		FIRSTKEYCARD=1,
		FIRST2KEYCARD=-1,
		FULLKEYCARD=1,
		CLUSTERRATIO=100,
		SEQUENTIAL_PAGES=0,
		DENSITY=0,
		NUMRIDS=1,
		NUMRIDS_DELETED=0,
		NUM_EMPTY_LEAFS=0,
		AVERAGE_RANDOM_PAGES=1.0,
		AVERAGE_SEQUENCE_GAP=0.0,
		AVERAGE_SEQUENCE_PAGES=0.0,
		DATAPARTITION_CLUSTERFACTOR=1.0,
		INDCARD=1
	WHERE TABNAME ='PENDING_ARTICLES' AND INDNAME = 'PENDING_ARTICLES_PK' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.TABLES 
	SET CARD=0,
		NPAGES=0,
		FPAGES=1,
		OVERFLOW=0,
		ACTIVE_BLOCKS=0,
		AVGCOMPRESSEDROWSIZE=0,
		AVGROWCOMPRESSIONRATIO=0.0,
		PCTROWSCOMPRESSED=0.0,
		PCTPAGESSAVED=0.0
	WHERE TABNAME ='PENDING_ARTICLES' AND TABSCHEMA='santosh';

