--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "santosh"."PENDING_ART_TAGS" DROP CONSTRAINT "SQL120312132225100";

ALTER TABLE "santosh"."PENDING_ART_TAGS" DROP CONSTRAINT "PENDING_ART_TAGS_PK";

DROP TABLE "santosh"."PENDING_ART_TAGS";

CREATE TABLE "santosh"."PENDING_ART_TAGS" (
		"PID" VARCHAR(20) NOT NULL,
		"TAGS" VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1";

ALTER TABLE "santosh"."PENDING_ART_TAGS" ADD CONSTRAINT "PENDING_ART_TAGS_PK" PRIMARY KEY
	("PID",
	 "TAGS");

ALTER TABLE "santosh"."PENDING_ART_TAGS" ADD CONSTRAINT "SQL120312132225100" FOREIGN KEY
	("PID")
	REFERENCES "santosh"."PENDING_ARTICLES"
	("PID");

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ART_TAGS' AND COLNAME = 'PID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='PENDING_ART_TAGS' AND COLNAME = 'TAGS' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.INDEXES 
	SET NLEAF=1,
		NLEVELS=1,
		FIRSTKEYCARD=0,
		FIRST2KEYCARD=0,
		FULLKEYCARD=0,
		CLUSTERRATIO=100,
		SEQUENTIAL_PAGES=0,
		DENSITY=0,
		NUMRIDS=0,
		NUMRIDS_DELETED=0,
		NUM_EMPTY_LEAFS=0,
		AVERAGE_RANDOM_PAGES=0.0,
		AVERAGE_SEQUENCE_GAP=0.0,
		AVERAGE_SEQUENCE_PAGES=0.0,
		DATAPARTITION_CLUSTERFACTOR=1.0,
		INDCARD=0
	WHERE TABNAME ='PENDING_ART_TAGS' AND INDNAME = 'PENDING_ART_TAGS_PK' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.TABLES 
	SET CARD=0,
		NPAGES=0,
		FPAGES=1,
		OVERFLOW=0,
		ACTIVE_BLOCKS=0,
		AVGCOMPRESSEDROWSIZE=0,
		AVGROWCOMPRESSIONRATIO=0.0,
		PCTROWSCOMPRESSED=0.0,
		PCTPAGESSAVED=0.0
	WHERE TABNAME ='PENDING_ART_TAGS' AND TABSCHEMA='santosh';

