--<ScriptOptions statementTerminator=";"/>

DROP SEQUENCE "santosh"."REGISTERED_MEMBER_SEQ";

CREATE SEQUENCE "santosh"."REGISTERED_MEMBER_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

COMMENT ON SEQUENCE "santosh"."REGISTERED_MEMBER_SEQ" IS
'SEQUENCE TO GIVE REGISTERED MEMBERS ID';

