--<ScriptOptions statementTerminator=";"/>

DROP SEQUENCE "santosh"."SUPERVISOR_SEQ";

CREATE SEQUENCE "santosh"."SUPERVISOR_SEQ" AS INTEGER  START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 NO CYCLE CACHE 20 NO ORDER;

COMMENT ON SEQUENCE "santosh"."SUPERVISOR_SEQ" IS
'sequence to give sid';

