--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "santosh"."SUPERVISOR" DROP CONSTRAINT "SUPERVISOR_PK";

DROP TABLE "santosh"."SUPERVISOR";

CREATE TABLE "santosh"."SUPERVISOR" (
		"SID" VARCHAR(20) NOT NULL,
		"NAME" VARCHAR(30) NOT NULL,
		"EMAIL" VARCHAR(50) NOT NULL,
		"PASSWORD" VARCHAR(50) NOT NULL,
		"CATEGORY" VARCHAR(30)
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1";

ALTER TABLE "santosh"."SUPERVISOR" ADD CONSTRAINT "SUPERVISOR_PK" PRIMARY KEY
	("SID");

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='SUPERVISOR' AND COLNAME = 'EMAIL' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='SUPERVISOR' AND COLNAME = 'NAME' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='SUPERVISOR' AND COLNAME = 'PASSWORD' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='SUPERVISOR' AND COLNAME = 'SID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='SUPERVISOR' AND COLNAME = 'CATEGORY' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.INDEXES 
	SET NLEAF=1,
		NLEVELS=1,
		FIRSTKEYCARD=0,
		FIRST2KEYCARD=-1,
		FULLKEYCARD=0,
		CLUSTERRATIO=100,
		SEQUENTIAL_PAGES=0,
		DENSITY=0,
		NUMRIDS=0,
		NUMRIDS_DELETED=0,
		NUM_EMPTY_LEAFS=0,
		AVERAGE_RANDOM_PAGES=0.0,
		AVERAGE_SEQUENCE_GAP=0.0,
		AVERAGE_SEQUENCE_PAGES=0.0,
		DATAPARTITION_CLUSTERFACTOR=1.0,
		INDCARD=0
	WHERE TABNAME ='SUPERVISOR' AND INDNAME = 'SUPERVISOR_PK' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.TABLES 
	SET CARD=0,
		NPAGES=0,
		FPAGES=1,
		OVERFLOW=0,
		ACTIVE_BLOCKS=0,
		AVGCOMPRESSEDROWSIZE=0,
		AVGROWCOMPRESSIONRATIO=0.0,
		PCTROWSCOMPRESSED=0.0,
		PCTPAGESSAVED=0.0
	WHERE TABNAME ='SUPERVISOR' AND TABSCHEMA='santosh';

