--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "santosh"."VALIDATED_ARTICLES" DROP CONSTRAINT "SQL120312135108170";

ALTER TABLE "santosh"."VALIDATED_ARTICLES" DROP CONSTRAINT "SQL120312135213290";

ALTER TABLE "santosh"."VALIDATED_ARTICLES" DROP CONSTRAINT "SQL120312135401950";

ALTER TABLE "santosh"."VALIDATED_ARTICLES" DROP CONSTRAINT "VALIDATED_ARTICLES_PK";

DROP TABLE "santosh"."VALIDATED_ARTICLES";

CREATE TABLE "santosh"."VALIDATED_ARTICLES" (
		"VID" VARCHAR(20) NOT NULL,
		"FILE_PATH" VARCHAR(150) NOT NULL,
		"NAME" VARCHAR(60) NOT NULL DEFAULT ' ',
		"RATING" INTEGER NOT NULL DEFAULT 0,
		"CATEGORY" VARCHAR(30) NOT NULL,
		"VALIDATION_DATE" DATE NOT NULL DEFAULT CURRENT DATE,
		"VIEW_COUNT" INTEGER NOT NULL DEFAULT 0,
		"SID" VARCHAR(20) NOT NULL,
		"RID" VARCHAR(20) NOT NULL,
		"ISSUE_NAME" VARCHAR(20) DEFAULT NULL,
		"AUTHOR_NAME" VARCHAR(20) NOT NULL DEFAULT '',
		"PAGENO" INTEGER NOT NULL DEFAULT 0,
		"CHOSEN" VARCHAR(5) DEFAULT 'No',
		"PICTURE_PATH" VARCHAR(150),
		"SNIPPET" VARCHAR(500),
		"PDF_PATH" VARCHAR(150)
	)
	DATA CAPTURE NONE 
	IN "USERSPACE1";

ALTER TABLE "santosh"."VALIDATED_ARTICLES" ADD CONSTRAINT "VALIDATED_ARTICLES_PK" PRIMARY KEY
	("VID");

ALTER TABLE "santosh"."VALIDATED_ARTICLES" ADD CONSTRAINT "SQL120312135108170" FOREIGN KEY
	("RID")
	REFERENCES "santosh"."REGISTERED_MEMBERS"
	("RID");

ALTER TABLE "santosh"."VALIDATED_ARTICLES" ADD CONSTRAINT "SQL120312135213290" FOREIGN KEY
	("SID")
	REFERENCES "santosh"."SUPERVISOR"
	("SID");

ALTER TABLE "santosh"."VALIDATED_ARTICLES" ADD CONSTRAINT "SQL120312135401950" FOREIGN KEY
	("ISSUE_NAME")
	REFERENCES "santosh"."ISSUES"
	("NAME");

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'AUTHOR_NAME' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'CATEGORY' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'FILE_PATH' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'NAME' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'PAGENO' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'RATING' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'RID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'SID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'VALIDATION_DATE' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'VID' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=4,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'VIEW_COUNT' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'CHOSEN' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'ISSUE_NAME' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'PDF_PATH' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'PICTURE_PATH' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.COLUMNS 
	SET COLCARD=0,
		AVGCOLLEN=5,
		NUMNULLS=0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND COLNAME = 'SNIPPET' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.INDEXES 
	SET NLEAF=1,
		NLEVELS=1,
		FIRSTKEYCARD=3,
		FIRST2KEYCARD=-1,
		FULLKEYCARD=3,
		CLUSTERRATIO=100,
		SEQUENTIAL_PAGES=0,
		DENSITY=0,
		NUMRIDS=3,
		NUMRIDS_DELETED=0,
		NUM_EMPTY_LEAFS=0,
		AVERAGE_RANDOM_PAGES=1.0,
		AVERAGE_SEQUENCE_GAP=0.0,
		AVERAGE_SEQUENCE_PAGES=0.0,
		DATAPARTITION_CLUSTERFACTOR=1.0,
		INDCARD=3
	WHERE TABNAME ='VALIDATED_ARTICLES' AND INDNAME = 'VALIDATED_ARTICLES_PK' AND TABSCHEMA='santosh';

UPDATE SYSSTAT.TABLES 
	SET CARD=0,
		NPAGES=0,
		FPAGES=1,
		OVERFLOW=0,
		ACTIVE_BLOCKS=0,
		AVGCOMPRESSEDROWSIZE=0,
		AVGROWCOMPRESSIONRATIO=0.0,
		PCTROWSCOMPRESSED=0.0,
		PCTPAGESSAVED=0.0
	WHERE TABNAME ='VALIDATED_ARTICLES' AND TABSCHEMA='santosh';

